services:
  db:
    image: postgres:16.9
    container_name: pgres-db-teo5
    environment:
      POSTGRES_DB: teo5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpass
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: